import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import { Button } from "./components/button";
import { TestimonialSection } from "./components/testimonial-section";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Smartwatch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url('/images/dark-background.png')] bg-cover bg-center bg-no-repeat `}
      >
        <main className="flex-grow container mx-auto p-4 ">{children}</main>
        <TestimonialSection />
        <div className="flex flex-col items-center justify-center mt-20 py-30 text-center">
          <h2 className="text-5xl lg:text-6xl font-bold text-[#000957] mb-2 text-[#EFE4D2] ">
            Special Bonus Just For You !
          </h2>
          <p className="text-lg text-white">
            Use code{" "}
            <span className="font-semibold text-red-500  mb-3">SMART10</span> at
            Plus, receive an exclusive strap worth Rp250.000 for FREE!
          </p>
          <p className="text-md text-gray-500 italic">
            *Limited time offer. Don&apos;t miss out!
          </p>
          <div>
            <Button size="xl">Buy Now</Button>
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
